"use client";

import { FormEvent, useState } from "react";
import { ArrowRight } from "lucide-react";

export function InquiryForm() {
  const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle");
  const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("loading"); setMessage(""); const form = event.currentTarget; const body = Object.fromEntries(new FormData(form).entries()); try { const response = await fetch("/api/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(); form.reset(); setStatus("success"); setMessage("Thank you. The Lex Interface team will be in touch."); } catch { setStatus("error"); setMessage("We could not submit the enquiry. Please call the office directly."); } }
  return <form className="contact-form" onSubmit={submit}><p className="section-label">Private &amp; considered</p><h3>Tell us where it begins.</h3><div className="form-grid"><div className="field"><label htmlFor="full_name">Full name *</label><input id="full_name" name="full_name" required autoComplete="name" /></div><div className="field"><label htmlFor="email">Email *</label><input id="email" name="email" type="email" required autoComplete="email" /></div><div className="field"><label htmlFor="phone">Telephone *</label><input id="phone" name="phone" required autoComplete="tel" /></div><div className="field"><label htmlFor="nature">Nature of matter</label><select id="nature" name="nature" defaultValue="Dispute Resolution"><option>Dispute Resolution</option><option>General Corporate &amp; Commercial</option><option>Intellectual Property</option><option>Labour &amp; Employment</option><option>Mergers &amp; Acquisitions</option><option>Real Estate</option><option>Other / Not sure</option></select></div><div className="field full"><label htmlFor="message">How can we help?</label><textarea id="message" name="message" placeholder="Please share the broad context, timeline and preferred next step. Avoid confidential details." /></div></div><p className="form-note">Please avoid sharing confidential details in this form. Submitting an enquiry does not create an attorney-client relationship.</p><button className="btn dark" type="submit" disabled={status === "loading"}>{status === "loading" ? "Sending…" : <>Send enquiry <ArrowRight size={16} /></>}</button>{message && <p className={`form-status ${status}`}>{message}</p>}</form>;
}
