"use client";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, BriefcaseBusiness, Building2, Contact, Gavel, Home, Mail, UsersRound } from "lucide-react";
import { usePathname } from "next/navigation";
import { BrandMark } from "./BrandMark";
const links=[{href:"/",label:"Home",icon:Home},{href:"/firm",label:"About us",icon:Building2},{href:"/practice",label:"Practice areas",icon:Gavel},{href:"/people",label:"Our team",icon:UsersRound},{href:"/careers",label:"Careers",icon:BriefcaseBusiness},{href:"/contact",label:"Contact us",icon:Contact}];
export function SiteShell({children}:{children:React.ReactNode}){const pathname=usePathname();return <div className="shell"><header className="site-header"><Link href="/" className="site-brand" aria-label="Lex Interface home"><Image className="logo-image" src="/lex-interface-logo.png" alt="Lex Interface logo" width={1280} height={1280} priority/><span><strong>LEX INTERFACE</strong><small>ADVOCATES &amp; LEGAL CONSULTANTS</small></span></Link><nav className="site-nav">{links.map(({href,label})=><Link key={href} href={href} className={pathname===href?"active":""}>{label}</Link>)}</nav><Link className="header-contact" href="/contact">Contact us <Mail size={16}/></Link></header><nav className="mobile-nav">{links.map(({href,label})=><Link key={href} href={href} className={pathname===href?"active":""}>{label}</Link>)}</nav><main className="content">{children}<Footer/></main></div>}
function Footer(){return <footer className="footer"><div className="page-wrap"><div className="footer-inner"><BrandMark/><div className="footer-links"><a href="https://www.linkedin.com/company/lex-interface/" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={12}/></a><Link href="/contact">Reach us <ArrowUpRight size={12}/></Link></div></div><p className="disclaimer">© 2026 Lex Interface. Prevailing Bar Council of India Rules do not permit advocates to solicit or advertise. Content on this site is for information only and is not legal advice. Visiting or submitting an enquiry does not create an attorney-client relationship.</p></div></footer>}
